name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - '.version'
      - 'Makefile'
      - 'cuda10.2-cudnn7-ubuntu2004-dev.Dockerfile'
      - 'cuda10.2-cudnn7-ubuntu2004-runtime.Dockerfile'

jobs:
  build-cuda102-cudnn7-ubuntu2004-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make build-cuda10.2-cudnn7-ubuntu2004-runtime

  build-cuda102-cudnn7-ubuntu2004-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make build-cuda10.2-cudnn7-ubuntu2004-dev
